In [1]:
import numpy as np
import itertools

In [2]:
def is_k_AND_equal_zero(k_elements):
    
    k_AND = (1<<12)-1
    for element in k_elements:
        k_AND &= element
    
    return (k_AND == 0)

In [3]:
def brute_force(arr, k):
    """
    Using brute force to get the output
    """
    idx = np.arange(0, len(arr), 1)
    combinations = itertools.combinations(idx, k)
    
    for com in combinations:
        if is_k_AND_equal_zero(arr[list(com)]):
            explain = f'{arr[list(com)]}'
            return 'YES', explain
            break
    else:
        return 'NO', None

In [4]:
def generate_one_test(n, k, low_ai, high_ai):
    
    arr = np.random.randint(low=low_ai, high=high_ai+1, size=n)
    return arr

In [9]:
def generate_multiple_tests(low_n, high_n, num_tests, low_ai=0, high_ai=4095):
    ns = np.random.randint(low=low_n, high=high_n, size=num_tests)
    for i in range(len(ns)):
        k = np.random.randint(low=1, high=ns[i]+1)
        arr = generate_one_test(ns[i], k, low_ai, high_ai)
        output, explain = brute_force(arr, k)
        print(f'Input:\n{ns[i]} {k}\n{arr}\nOutput:\n{output}')
        if explain:
            print('Explain:\nk elements are:', explain)
        print()

In [13]:
generate_multiple_tests(low_n=1, high_n=20, num_tests=3)

Input:
10 3
[ 771  680 2441   22 3359  862 3240 2267 4048 3025]
Output:
YES
Explain:
k elements are: [ 771  680 2441]

Input:
12 10
[2922 1366 1501 1415 2846 1237   95  102  550  542  718 1231]
Output:
YES
Explain:
k elements are: [2922 1366 1501 1415 2846 1237   95  102  550  542]

Input:
9 1
[1980 2142  426  950 3340 2443 3278 1500 3258]
Output:
NO



## Generate test from distributions

### 10 tests where $0 < n \leq 100$ 

In [19]:
generate_multiple_tests(low_n=1, high_n=100, num_tests=10)

Input:
93 76
[  43 3019 2861 2657 2141 1982  458 2294 1113 1568 1861  308 2728 2768
 2939 1564  254 2010 4084  985  827 2467 2296 3500 2006 1502 2421  992
 3607 1808 2692  510 2700 2392 2266  164  770 1463  762 4050 2567 2687
  349 2577 2071 1181 1165 2567  212 2366 3446 1709  792 3771 2160  213
 3007 2460 1387 1767  714 3700 3745 2022 2688 4088  731 2469 3732 1127
  500 3912 3512 1639 2682 1591  409 3516  585  111 3036  235  419 3627
 1291  568  725 3246 2908 1761 3344 2204 2486]
Output:
YES
Explain:
k elements are: [  43 3019 2861 2657 2141 1982  458 2294 1113 1568 1861  308 2728 2768
 2939 1564  254 2010 4084  985  827 2467 2296 3500 2006 1502 2421  992
 3607 1808 2692  510 2700 2392 2266  164  770 1463  762 4050 2567 2687
  349 2577 2071 1181 1165 2567  212 2366 3446 1709  792 3771 2160  213
 3007 2460 1387 1767  714 3700 3745 2022 2688 4088  731 2469 3732 1127
  500 3912 3512 1639 2682 1591]

Input:
92 56
[3132 2360 1392  438 3262  486 2830 2945 1802  317  331    7 1715  568
 3331

### 10 tests where $100 < n \leq 10000$ 

In [16]:
generate_multiple_tests(low_n=100, high_n=10000, num_tests=10)

Input:
816 721
[1150    9 3711 2155  334 2869  128 1659   45 2598 1892 3226 1648 3977
 1002  263 3976 2122 2117 3209 1643  423  169 2063 3848 1430 3744 2458
 1854 2577 3605 2481 1164  167 1782 3111 3436  132 1872  515   18 3567
 2055 3113 3624 1568 3199 1088 1448  626 3588  120 3600 3343 1995  297
 3442  235 3115 1327  628  786 2162 2952 3423 3514 3559  647 3673  191
  813 1375 2961 1134  838 1557 1611  902 2256 1605 1124 1280 2645    0
 1648 2772 1391 3986 3795 2091  180 1485 3845 2649  950  548  219 3107
 1203 3883 2621 3896 3161 1133 3750 1072  708 3815 3442  338 1246  122
 2164 3298 3335 3685 2337  799 1360 2906 3180 1700 2238 2685 1950 1737
 3100 1131 1741  595 1845  598 4023 2358  770 2077 3589 1360 2685 2412
 1042 2282 2857 2170 1637 1281 1766 3369  810 3368  414 2672 3754 2266
 3303 1179  748 1677 2827 1230 2140 3820 2683  146  721 2814 1351 1778
 4065 1408 1744 2817 2882 1342 2838 1907 2701  649 3218 1581 1291 2954
 2208 1146 3331 3028 3638 3673 2504 3548  315    2  581 3466 1

### 10 tests where $10000 < n \leq 20000$ 

In [20]:
generate_multiple_tests(low_n=10000, high_n=20000, num_tests=10)

Input:
10279 4140
[ 924 1848 3829 ... 1116 1243 3819]
Output:
YES
Explain:
k elements are: [ 924 1848 3829 ... 3500 3560 1367]

Input:
15440 4961
[1001 3964 2870 ... 3979 3675 1685]
Output:
YES
Explain:
k elements are: [1001 3964 2870 ... 2508 2294 2980]

Input:
11356 7437
[2593  145 2282 ...  352 1481  768]
Output:
YES
Explain:
k elements are: [2593  145 2282 ... 1945 3776 2624]

Input:
16017 3822
[2451 3028 3282 ... 1413  832 1325]
Output:
YES
Explain:
k elements are: [2451 3028 3282 ... 2658 2597 2496]

Input:
17848 16451
[2894 1575 1634 ...  415 2754   99]
Output:
YES
Explain:
k elements are: [2894 1575 1634 ... 2463 3806 1434]

Input:
13929 559
[ 439  266 2951 ... 2970  404  622]
Output:
YES
Explain:
k elements are: [ 439  266 2951  184 2949 3763 1963 3844 1930   14  816 3590  187 3229
 2296 3313 3526 2285 3165 2584 1228 3755  571 4038 3258 3706 3194 3414
 3103  171 1549 1731  410 1413 3397  393 3087 2324 2465 1447 3564 3412
 1830 2565 2807  257   72 1164 2389 3727 1749 1292  565 